(global-set-key (kbd "C-c C-c") 'comment-region)
(global-set-key (kbd "C-c M-c") 'uncomment-region)
(global-set-key (kbd "C-c o") 'bury-buffer)
(global-set-key (kbd "C-c k") 'kill-this-buffer)
(global-set-key (kbd "C-c j") 'join-line)
(global-set-key (kbd "C-c C-k") 'copy-line)
(global-set-key (kbd "C-c M-s") 'occur)

(global-set-key [f1] 'ansi-term)
(global-set-key [f11] 'toggle-fullscreen)
